### ISSUE TITLE
Create a copy of an object: use object rest/spread

### ISSUE THREAD

**Issue by mathiasbynens** [sdras/object-explorer#9]
I like the `Object.assign` example to create a copy of an object. 👍

Can we show [object spread](https://developers.google.com/web/updates/2017/06/object-rest-spread) too? In many cases, it’s a more elegant solution than `Object.assign`. (There are some differences but they don’t matter in common scenarios.)

**Comment by devxom** [comment]
It may be worth to divide the methods into `ES5` and `ES6+`?

**Comment by sdras** [comment]
Yeah I like the idea of a little extra info there for those seeking it out.

As for the followup question, there may be a way I tag ES5 and ES6 in the future, but that's a separate issue, and very low priority. I certainly won't divide it up that way though, because 1) it's not documentation, as stated in the readme, and 2) it's not a very beginner-friendly way to explore. All of that information is in the documentation which is linked to from every method.

**Comment by mathiasbynens** [comment]
Version numbers don’t matter. +1 to not making the divide between any two ECMAScript versions.

**Comment by sdras** [comment]
Fixed!
